-- 사용자
CREATE TABLE IF NOT EXISTS `scamguard`.`users`
(
    `id`       INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '고유 ID',
    `login_id` VARCHAR(255) NOT NULL UNIQUE COMMENT '로그인 ID',
    `login_pw` VARCHAR(255) NOT NULL COMMENT '로그인 PW',
    `name`     VARCHAR(255) NOT NULL COMMENT '이름',
    `email`    VARCHAR(255) NOT NULL UNIQUE COMMENT '이메일',
    `type`     VARCHAR(255) NOT NULL COMMENT '사용자, 어드민',
    `status`   VARCHAR(255) NOT NULL COMMENT 'ACTIVE, INACTIVE, SUSPENDED',
    `created_at`    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일자',
    `updated_at`    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일자',
    PRIMARY KEY (`id`)
);
